name: Deploy site to gh-pages

on:
  push:
    branches:
      - master

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
          submodules: 'recursive'

      - name: Setup Node
        uses: actions/setup-node@v2-beta
        with:
          node-version: '12'

      - name: Run Install
        run: |
          npm install
        working-directory: ./parliament

      - name: Build production site
        env:
          GATSBY_SOURCE: ${{ secrets.GATSBY_SOURCE }}
          GATSBY_SOURCE_BRANCH: ${{ secrets.GATSBY_SOURCE_BRANCH }}
          GATSBY_SOURCE_PATTERNS: 'docs/**/*'
          GATSBY_SITE_PATH_PREFIX: '/magento2-page-builder-docs'
        run: |
          npm run build:prod
        working-directory: ./parliament

      - name: Deploy to gh-pages
        uses: Cecilapp/GitHub-Pages-deploy@master
        env:
          BUILD_DIR: ./parliament/public/docs/
          EMAIL: ${{ secrets.EMAIL }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
